name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          SHOW_TITLE: true
          COMMIT_BY_ME: true
          SHOW_LINES_OF_CODE: true
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
